### ISSUE TITLE
natives dependency fails on startup

### ISSUE THREAD

**Issue by derhuerst** [evansiroky/gtfs-sequelize#62]
```shell
mkdir foo
cd foo
npm init --yes
npm i gtfs-sequelize@3.0.1
node -v
# v12.22.10
node -r 'gtfs-sequelize'
# fs.js:36
# } = primordials;
#     ^
# 
# ReferenceError: primordials is not defined
#     at fs.js:36:5
#     at req_ (/Users/j/playground/gtfs-sequelize/node_modules/natives/index.js:143:24)
#     at Object.req [as require] (/Users/j/playground/gtfs-sequelize/node_modules/natives/index.js:55:10)
#     at Object.<anonymous> (/Users/j/playground/gtfs-sequelize/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
#     at Module._compile (internal/modules/cjs/loader.js:999:30)
#     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
#     at Module.load (internal/modules/cjs/loader.js:863:32)
#     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
#     at Module.require (internal/modules/cjs/loader.js:887:19)
#     at require (internal/modules/cjs/helpers.js:74:18)
```

**Comment by derhuerst** [comment]
With Node.js v18 too:

```shell
node -v
# v18.3.0
node -r 'gtfs-sequelize'
# fs.js:47
# } = primordials;
#     ^
# 
# ReferenceError: primordials is not defined
#     at fs.js:47:5
#     at req_ (/Users/j/playground/gtfs-sequelize/node_modules/natives/index.js:143:24)
#     at Object.req [as require] (/Users/j/playground/gtfs-sequelize/node_modules/natives/index.js:55:10)
#     at Object.<anonymous> (/Users/j/playground/gtfs-sequelize/node_modules/fstream/node_modules/graceful-fs/fs.js:1:37)
#     at Module._compile (node:internal/modules/cjs/loader:1105:14)
#     at Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
#     at Module.load (node:internal/modules/cjs/loader:981:32)
#     at Module._load (node:internal/modules/cjs/loader:827:12)
#     at Module.require (node:internal/modules/cjs/loader:1005:19)
#     at require (node:internal/modules/cjs/helpers:102:18)
```
